modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory. 26 for 1.14.2, 27 for 1.14.3, 28 for 1.14.4. 29,30,31 for 1.15, 1.15.2/3

[[mods]] #mandatory
modId="fireproofitems" #mandatory
version="1.0" #mandatory
displayName="Fireproof Items Mod" #mandatory
credits="Original version by Grillo" #optional
license="All rights reserved"
description='''
A mod to keep your items safe from lava
'''